### ISSUE TITLE
How to set location?

### ISSUE THREAD

**Issue by Voluntaryism** [deoxxa/tinder#3]
The location is set by default to the last login location on Tinder, so how do you override it to set the location for a latitude and longitude?

**Comment by deoxxa** [comment]
https://github.com/deoxxa/tinder/blob/master/index.js#L257-L277

**Comment by deoxxa** [comment]
![](https://i.imgur.com/FDg6wPa.png)

lol

**Comment by Voluntaryism** [comment]
I may have been a little _too_ persistent. And thank you for your comment, I'll try to implement that code
